version: "3.8"
services:
  # amera-dns:
  #   container_name: amera-dns
  #   image: andyshinn/dnsmasq:latest
  #   command: >
  #    --log-queries
  #    --log-facility=-
  #    --address=/dev.amera.local/127.0.0.1
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     - amera-net
  # socat:
  #   image: alpine/socat
  #   command: tcp-listen:80,fork,reuseaddr tcp-connect:host.docker.internal:9000
  #   environment:
  #     - VIRTUAL_HOST=dev.amera.local
  #     - VIRTUAL_PORT=80
  #   expose:
  #     - 80
  amera-nginx:
    container_name: amera-nginx
    image: nginx:alpine
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "1"
    ports:
      - 9000:9000
      - 9443:443
#    command: [nginx-debug, "-g", "daemon off;"] # Uncomment if want to enable debug mode
    networks:
      amera-net:
        aliases:
          - amera-tmp
          - amera-web-share
          - amera-web-auth
          # - amera-web-main
          # - amera-web-notifications
    volumes:
      - ../web:/app/main:ro
      - ../web-share:/app/share:ro
      - ../web-api/config/dev-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # - amera-dns
      - amera-web-api
      # - amera-web-auth
      - amera-web-db
      - amera-eventserver
  amera-web-main:
    container_name: amera-web-main
    image: amera-web-main:latest
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "1"
    build:
      context: ../web
      dockerfile: Dockerfile.dev
    networks:
      - amera-net
    expose:
      - 5001
    volumes:
      - ../web:/app
      - web-main-python-packages:/root/.local/share
    command: ["pipenv", "run", "dev"]
  amera-web-share:
    container_name: amera-web-share
    image: amera-web-share:latest
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "1"
    user: node
    build:
      context: ../web-share
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PUBLIC_URL: /share
    networks:
      - amera-net
    expose:
      - 3000
    volumes:
      - ../web-share:/home/node/app
    stdin_open: true
    command: ["yarn", "start"]
  # amera-web-auth:
  #    container_name: amera-web-auth
  #    image: amera-web-auth:latest
  #    restart: always
  #    logging:
  #      options:
  #        max-size: "500k"
  #        max-file: "1"
  #    build:
  #      context: ../web-api
  #      dockerfile: Dockerfile.dev
  #    depends_on:
  #      - amera-web-db
  #    networks:
  #      - amera-net
  #    expose:
  #      - 5000
  #    volumes:
  #      - ../web-api:/app
  #      - web-api-python-packages:/root/.local/share
  #    command: ['pipenv', 'run', 'docker']
  amera-web-api:
    container_name: amera-web-api
    image: amera-web-api:latest
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "1"
    build:
      context: ../web-api
      dockerfile: Dockerfile
    depends_on:
      - amera-web-db
    networks:
      - amera-net
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ../web-api:/app
      - web-api-python-packages:/root/.local/share
    command: ["pipenv", "run", "local"]

  amera-web-db:
    container_name: amera-web-db
    image: postgres:latest
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "1"
    volumes:
      - ../web-api/datasource/postgresql/members.sql:/docker-entrypoint-initdb.d/1-members.sql
      - ../web-api/datasource/postgresql/group.sql:/docker-entrypoint-initdb.d/2-group.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-07-21.sql:/docker-entrypoint-initdb.d/3-1-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-08-13.sql:/docker-entrypoint-initdb.d/3-2-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-08-14.sql:/docker-entrypoint-initdb.d/3-3-schema-updates.sql
      - ../web-api/datasource/postgresql/scheduler.sql:/docker-entrypoint-initdb.d/4-scheduler.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-08-15-schedulersetting.sql:/docker-entrypoint-initdb.d/5-1-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-08-26.sql:/docker-entrypoint-initdb.d/5-2-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-08-29.sql:/docker-entrypoint-initdb.d/5-3-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-01.sql:/docker-entrypoint-initdb.d/5-4-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-02.sql:/docker-entrypoint-initdb.d/5-5-schema-updates.sql
      - ../web-api/datasource/postgresql/member_contact.sql:/docker-entrypoint-initdb.d/7-member_contact.sql
      - ../web-api/datasource/postgresql/country_code.sql:/docker-entrypoint-initdb.d/8-country_code.sql
      - ../web-api/datasource/postgresql/job-title.sql:/docker-entrypoint-initdb.d/9-job-title.sql
      - ../web-api/datasource/postgresql/amera_tos.sql:/docker-entrypoint-initdb.d/a-amera_tos.sql
      - ../web-api/datasource/postgresql/member_tos.sql:/docker-entrypoint-initdb.d/b-member-tos.sql
      - ../web-api/datasource/postgresql/cell_token.sql:/docker-entrypoint-initdb.d/c-cell-token.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-04_member_avatar.sql:/docker-entrypoint-initdb.d/d-1-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-07.sql:/docker-entrypoint-initdb.d/d-2-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-09.sql:/docker-entrypoint-initdb.d/d-3-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-17.sql:/docker-entrypoint-initdb.d/d-4-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-26_member.sql:/docker-entrypoint-initdb.d/d-5-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-25.sql:/docker-entrypoint-initdb.d/d-6-schema-updates.sql
      - ../web-api/datasource/postgresql/promo_codes.sql:/docker-entrypoint-initdb.d/d-7-promo-codes.sql
      - ../web-api/datasource/postgresql/department.sql:/docker-entrypoint-initdb.d/d-8-department.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-09-28_deps_to_member.sql:/docker-entrypoint-initdb.d/d-9-schema-updates.sql
      - ../web-api/datasource/postgresql/member_achievement.sql:/docker-entrypoint-initdb.d/e-1-member_achievement.sql
      - ../web-api/datasource/postgresql/member_profile.sql:/docker-entrypoint-initdb.d/e-2-member_profile.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-10-08_1_titles.sql:/docker-entrypoint-initdb.d/e-3-unset-titles.sql
      - ../web-api/datasource/postgresql/email_token.sql:/docker-entrypoint-initdb.d/e-4-schema-updates.sql
      - ../web-api/datasource/postgresql/file_tree.sql:/docker-entrypoint-initdb.d/e-5-file_tree.sql
      - ../web-api/datasource/postgresql/file_tree_item.sql:/docker-entrypoint-initdb.d/e-6-file_tree_item.sql
      - ../web-api/datasource/postgresql/file_share.sql:/docker-entrypoint-initdb.d/e-7-file_share.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-10-22_invites.sql:/docker-entrypoint-initdb.d/e-8-schema-updates.sql
      - ../web-api/datasource/postgresql/event.sql:/docker-entrypoint-initdb.d/f-1-event.sql
      - ../web-api/datasource/postgresql/event_invite.sql:/docker-entrypoint-initdb.d/f-2-event_invite.sql
      - ../web-api/datasource/postgresql/event_reschedule.sql:/docker-entrypoint-initdb.d/f-3-event_reschedule.sql
      - ../web-api/datasource/postgresql/mail.sql:/docker-entrypoint-initdb.d/f-4-mail.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-12-04.sql:/docker-entrypoint-initdb.d/f-5-schema-updates.sql
      - ../web-api/datasource/postgresql/schema-updates-2020-12-17.sql:/docker-entrypoint-initdb.d/f-6-schema-updates.sql
      - ../web-api/datasource/postgresql/test-country.dev.sql:/docker-entrypoint-initdb.d/z-1-test-country.sql
      - ../web-api/datasource/postgresql/test-member.dev.sql:/docker-entrypoint-initdb.d/z-2-test-member.sql
      - ../web-api/datasource/postgresql/test-schedule.dev.sql:/docker-entrypoint-initdb.d/z-3-test-schedule.sql
      - ../web-api/datasource/postgresql/test-amera-tos.dev.sql:/docker-entrypoint-initdb.d/z-4-test-amera-tos.dev.sql.sql
      - ../web-api/datasource/postgresql/test-promo-codes.dev.sql:/docker-entrypoint-initdb.d/z-5-test-promo-codes.dev.sql
      - ../web-api/datasource/postgresql/test-achievements.dev.sql:/docker-entrypoint-initdb.d/z-6-test-achievements.dev.sql
      - ../web-api/datasource/postgresql/test-fileshare.sql:/docker-entrypoint-initdb.d/z-7-test-fileshare.dev.sql
      - ../web-api/datasource/postgresql/test-event.dev.sql:/docker-entrypoint-initdb.d/z-8-test-event.dev.sql
    environment:
      POSTGRES_DB: ameraiot
      POSTGRES_USER: amera
      POSTGRES_PASSWORD: amera
    networks:
      - amera-net
    ports:
      - 5432:5432

# Kafka and Zookeeper Single Deploy
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - amera-net
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - amera-net

  amera-eventserver:
    container_name: amera-eventserver
    image: amera-eventserver:latest
    restart: always
    build:
      context: ../web-api
      dockerfile: Dockerfile
    depends_on:
      - amera-web-api
    networks:
      - amera-net
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ../web-api:/app
      - web-eventserver-python-packages:/root/.local/share
#    command: [ "uvicorn", "--app-dir=./eventserver", "test-star:app", "--host", "0.0.0.0", "--port", "4000", "--reload" ]
    command: ["gunicorn", "--chdir", "eventserver", "sse:app", "--reload", "--bind=0.0.0.0:4000", "-k", "uvicorn.workers.UvicornWorker", "--log-level=DEBUG"]

  amera-call-consumer:
    container_name: amera-call-consumer
    image: amera-consumer:latest
    restart: always
    build:
      context: ../web-api
      dockerfile: Dockerfile
    networks:
      - amera-net
    volumes:
      - ../web-api:/app
      - web-consumer-call-python-packages:/root/.local/share
    environment:
      - AMERA_API_KAFKA.SERVER=kafka:9092
    depends_on:
      - kafka
      - zookeeper
      - amera-eventserver
#    command: [ "pipenv", "run", "calls"]
    command: [ "pipenv", "run", "dev-calls" ]


  amera-email-consumer:
    container_name: amera-email-consumer
    image: amera-consumer:latest
    restart: always
    build:
      context: ../web-api
      dockerfile: Dockerfile
    networks:
      - amera-net
    volumes:
      - ../web-api:/app
      - web-consumer-email-python-packages:/root/.local/share
    environment:
      - AMERA_API_KAFKA.SERVER=kafka:9092
    depends_on:
      - kafka
      - zookeeper
      - amera-eventserver
#    command: [ "pipenv", "run", "emails" ]
    command: ["pipenv", "run", "dev-email"]

  amera-sms-consumer:
    container_name: amera-sms-consumer
    image: amera-consumer:latest
    restart: always
    build:
      context: ../web-api
      dockerfile: Dockerfile
    networks:
      - amera-net
    volumes:
      - ../web-api:/app
      - web-consumer-sms-python-packages:/root/.local/share
    environment:
      - AMERA_API_KAFKA.SERVER=kafka:9092
    depends_on:
      - kafka
      - zookeeper
      - amera-eventserver
#    command: [ "pipenv", "run", "sms" ]
    command: [ "pipenv", "run", "dev-sms" ]



volumes:
  web-api-python-packages:
    name: amera-web-api-python-packages
  web-main-python-packages:
    name: amera-web-main-python-packages
  web-eventserver-python-packages:
    name: amera-web-eventserver-python-packages
  web-consumer-call-python-packages:
    name: amera-consumer-call-python-packages
  web-consumer-email-python-packages:
    name: amera-consumer-email-python-packages
  web-consumer-sms-python-packages:
    name: amera-consumer-sms-python-packages
networks:
  amera-net:
    name: amera-net
