bind = "0.0.0.0:5000"
env_name = "LOCAL"
app_name = "amera-api"
gunicorn_preload = false
log_level = "DEBUG"

[web]
session_expiration = 32400
cookie_secure = false
cookie_domain = "localhost"
cookie_path = "/"
cookie_name = "member_session"
domain = "ameraiot.com"
domains = [
    "ameraiot.com",
    "amerashare.com",
    "localhost"
]
access_control_allow_origin = "*"
member_invite_register_url = "/member/invite/register/{}"
member_forgot_password_url = "/login/reset/{}"
forgot_password_expiration = 600

[database]
host = "amera-web-db"
port = 5432
user = "amera"
password = "amera"
database = "ameraiot"
log_level = "DEBUG"

[smtp]
email_from = "support@ameraiot.com"
server = "secure.emailsrvr.com"
port = 465
tls = true
user = "support@ameraiot.com"
password = "${SMTP_PASSWORD}"

[services]
[services.aws]
region_name = "us-east-2"
access_key_id = "${AWS_ACCESS_KEY_ID}"
secret_access_key = "${AWS_SECRET_ACCESS_KEY}"
[services.twilio]
totp_length = 6
totp_lifetime_seconds=60

[storage]
[storage.s3]
bucket = "file-testing"
arn = "arn:aws:s3:::file-testing"
user = "file-upload-test"
file_location_host = "https://file-testing.s3.us-east-2.amazonaws.com"

[kafka]
server = "kafka:9092"

[kafka.topics]

member = 'member_activity'
files = 'drive_activity'
keygen = 'amerakey_activity'
auth = 'auth_activity'
mail = 'mail_activity'
registration = 'registration_activity'
contact = 'contact_activity'
calendar = 'calendar_activity'
member_change_password = 'member_activity'

[kafka.event_types]

[kafka.event_types.get]
file_download = 'file_download'
file_storage = 'retrieve_file'
member_file_cloud = 'retrieve_file_trees'
group_file_cloud = 'retrieve_trees_for_group'
file_storage_detail = 'retrieve_file_storage_detail'
download_storage_file = 'store_file_to_static'
file_group_resource = 'file_group_resource'
member_group_resource = 'retrieve_groups'
member_group_detail = 'retrieve_group_members'
group_crud = 'check_member_in_group'
retrieve_all_group_members = 'retrieve_all_group_members'
member_group_security = 'retrieve_group_security'
member_invite = 'get_member_invite'
valid_member_invite = 'get_valid_member_invite'
keygen_file_upload = 'retrieve_amerakey_picture'
keygen_resource_crud = 'retrieve_amerakey_binary'
member_login = 'member_login_session'
attempt_validate_session = 'attempt_validate_session'
contact_security = 'contact_security'
get_members = 'get_members'
event_invite_response = 'event_invite_response'
mail_base_resource = ''

[kafka.event_types.post]
member_change_password = 'change_password'
file_storage = 'file_upload'
member_file_cloud = 'create_file_trees'
member_share_file = 'share_file'
group_file_cloud = 'create_group_folder'
forgot_password = 'forgot_password'
member_group_resource = 'create_group'
group_crud = 'add_member_group'
group_member_invite = 'invite_member_to_group'
member_group_security = 'update_security_group'
member_invite = 'create_member_invite'
keygen_file_upload = 'amerakey_picture_create'
keygen_resource_crud = 'amerakey_derive'
member_login = 'member_login'
member_logout = 'member_logout'
forward_mail = 'forward_mail'
mail_attachment = 'save_attachment_draft'
mail_draft_compose = 'create_mail_draft'
mail_draft_send = 'mail_draft_send'
mail_starred = 'mail_starred'
delete_mail = 'delete_mail'
move_trash_to_origin = 'move_trash_to_origin'
move_trash_to_archive = 'move_trash_to_archive'
archive_mail = 'archive_mail'
move_archive_mail_to_origin = 'move_archive_mail_to_origin'
move_archive_to_trash = 'move_archive_to_trash'
create_mail_settings = 'create_mail_settings'
member_registration = 'member_registration'
create_contact = 'create_contact'
create_contact_security = 'create_contact_security'
create_event = 'create_event'
create_event_attachment = 'create_event_attachment'
invite_users_to_event = 'invite_users_to_event'
invite_single_user_event = 'invite_single_user_event'
calendar_event_status_update = 'calendar_event_status_update'
holiday_scheduled = 'holiday_scheduled'
schedule_settings_updated = 'schedule_settings_updated'
attempt_to_use_promo_code = 'attempt_to_use_promo_code'
reset_password_attempted = 'reset_password_attempted'
send_verification_code = 'send_verification_code'
create_signature = 'create_signature'

[kafka.event_types.put]
file_storage = 'file_edit'
member_file_cloud = 'change_file_tree'
member_file_bin = 'restore_file_bin'
member_share_file = 'copy_shared_file'
group_file_cloud = 'move_group_file'
group_file_bin = 'group_restore_from_bin'
member_invite = 'change_member_invite'
member_info_update = 'member_info_update'
update_member_contact = 'update_member_contact'
verify_sms_code = 'verify_sms_code'
edit_event = 'edit_event'
group_membership_response = 'group_membership_response'
contact_request_response = 'contact_request_response'

[kafka.event_types.delete]
file_storage = 'file_delete'
member_file_cloud = 'send_files_to_bin'
member_file_bin = 'delete_file_bin'
member_share_file = 'unshare_file'
group_file_cloud = 'delete_group_file'
group_file_bin = 'delete_group_file_bin'
member_group_resource = 'delete_group'
group_crud = 'remove_member_from_group'
mail_attachment = 'delete_attachment_draft'  # TODO: NOT IN USE
mail_draft_delete = 'mail_draft_delete'
delete_contact = 'delete_contact'
delete_event_attachment = 'delete_event_attachment'
delete_event = 'delete_event'
delete_mail = 'delete_mail'


