name: API Build

on:
  push:
    tags:
      - v*

jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Master Branch Checkout
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.ECR_ACCESS_KEY }}
          secret_access_key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT }}
          repo: amera-web-api
          region: us-east-2
          tags: test,${{ steps.vars.outputs.tag }}
