name: Docker Build

on:
  push:
    tags:
      - v*

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Master Branch Checkout
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.ECR_ACCESS_KEY }}
          secret_access_key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT }}
          repo: amera-web-api
          region: us-east-2
          tags: test,${{ steps.vars.outputs.tag }}
      # - uses: mr-smithers-excellent/docker-build-push@v4
      #   name: Build & Push Web API Container
      #   with:
      #     image: amera-web-api
      #     registry: 615749211894.dkr.ecr.us-east-2.amazonaws.com
      #     dockerfile: Dockerfile
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
