ALTER TABLE company
ALTER COLUMN place_id SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN address_1 SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN address_2 SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN city SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN state SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN state_code_id SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN postal SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN country_code_id SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN main_phone SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN main_phone_ext SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN primary_url SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN logo_storage_id SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN province SET DEFAULT NULL;

ALTER TABLE company
ALTER COLUMN email SET DEFAULT NULL;