ALTER TABLE member_session
   ADD COLUMN  remote_ip_address           VARCHAR(64)     ,
   ADD COLUMN  remote_name                 VARCHAR(128),
   ADD COLUMN  remote_continent_code       VARCHAR(2),
   ADD COLUMN  remote_country_name         VARCHAR(128),
   ADD COLUMN  remote_country_code_2       VARCHAR(2),
   ADD COLUMN  remote_country_code_3       VARCHAR(2),
   ADD COLUMN  remote_country_code_id      INTEGER,
   ADD COLUMN  remote_country_phone        INTEGER,
   ADD COLUMN  remote_region_name          VARCHAR(128),
   ADD COLUMN  remote_region_code          VARCHAR(5),
   ADD COLUMN  remote_city_name            VARCHAR(128),
   ADD COLUMN  remote_postal_code          VARCHAR(64),
   ADD COLUMN  remote_latitude             FLOAT,
   ADD COLUMN  remote_longitude            FLOAT,
   ADD COLUMN  remote_timezone_name        VARCHAR(64),
   ADD COLUMN  remote_timezone_utc_offset  INTEGER,
   ADD COLUMN  remote_language_id          INTEGER,
   ADD COLUMN  server_ip_address           VARCHAR(64),
   ADD COLUMN  server_name                 VARCHAR(128),
   ADD COLUMN  server_country_code_id      INTEGER,
   ADD COLUMN  gateway_ip_address          VARCHAR(64),
   ADD COLUMN  gateway_name                VARCHAR(128),
   ADD COLUMN  gateway_country_code_id     INTEGER,
   ADD COLUMN  original_url                VARCHAR(100)     ,
   ADD COLUMN  original_arguments          VARCHAR(2000)    ,
   ADD COLUMN  organization_name           VARCHAR(255),
   ADD COLUMN  organization_domain         VARCHAR(255),
   ADD COLUMN  organization_asn            VARCHAR(255),
   ADD COLUMN  organization_type           VARCHAR(255),
   ADD COLUMN  organization_route          VARCHAR(255),
   ADD COLUMN  carrier_name                VARCHAR(255),
   ADD COLUMN  carrier_mcc                 VARCHAR(255),
   ADD COLUMN  carrier_mnc                 VARCHAR(255),
   ADD COLUMN  user_agent                  VARCHAR(255),
   ADD COLUMN  user_device                 VARCHAR(255),
   ADD COLUMN  user_device_type            VARCHAR(255),
   ADD COLUMN  user_device_name            VARCHAR(64),
   ADD COLUMN  user_os                     VARCHAR(255),
   ADD COLUMN  user_os_type                VARCHAR(255),
   ADD COLUMN  user_os_version             VARCHAR(64),
   ADD COLUMN  user_browser                VARCHAR(255),
   ADD COLUMN  user_browser_type           VARCHAR(255),
   ADD COLUMN  user_browser_version        VARCHAR(64),
   ADD COLUMN  ipregistry_response         JSONB;
