ALTER TABLE member_location
   ADD COLUMN address_1  VARCHAR(64) NULL,
   ADD COLUMN address_2  VARCHAR(64) NULL,
   ADD COLUMN state_code_id    INTEGER NULL,
   ADD COLUMN country_code_id INTEGER NULL,
   ADD COLUMN update_date   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;


