-- ------------------------------------------------------------------------------
-- Table:       state_code
-- Description: This table contains one row for every state or terretory
-- ------------------------------------------------------------------------------

INSERT INTO state_code ( id, country_code_id, short_name, name ) VALUES

                    (  01,   840,   'AL',  'Alabama'                       ),
                    (  02,   840,   'AK',  'Alaska'                        ),
                    (  04,   840,   'AZ',  'Arizona'                       ),
                    (  05,   840,   'AR',  'Arkansas'                      ),
                    (  06,   840,   'CA',  'California'                    ),
                    (  08,   840,   'CO',  'Colorado'                      ),
                    (  09,   840,   'CT',  'Connecticut'                   ),
                    (  10,   840,   'DE',  'Delaware'                      ),
                    (  11,   840,   'DC',  'District of Columbia'          ),
                    (  12,   840,   'FL',  'Florida'                       ),
                    (  13,   840,   'GA',  'Georgia'                       ),
                    (  15,   840,   'HI',  'Hawaii'                        ),
                    (  16,   840,   'ID',  'Idaho'                         ),
                    (  17,   840,   'IL',  'Illinois'                      ),
                    (  18,   840,   'IN',  'Indiana'                       ),
                    (  19,   840,   'IA',  'Iowa'                          ),
                    (  20,   840,   'KS',  'Kansas'                        ),
                    (  21,   840,   'KY',  'Kentucky'                      ),
                    (  22,   840,   'LA',  'Louisiana'                     ),
                    (  23,   840,   'ME',  'Maine'                         ),
                    (  24,   840,   'MD',  'Maryland'                      ),
                    (  25,   840,   'MA',  'Massachusetts'                 ),
                    (  26,   840,   'MI',  'Michigan'                      ),
                    (  27,   840,   'MN',  'Minnesota'                     ),
                    (  28,   840,   'MS',  'Mississippi'                   ),
                    (  29,   840,   'MO',  'Missouri'                      ),
                    (  30,   840,   'MT',  'Montana'                       ),
                    (  31,   840,   'NE',  'Nebraska'                      ),
                    (  32,   840,   'NV',  'Nevada'                        ),
                    (  33,   840,   'NH',  'New Hampshire'                 ),
                    (  34,   840,   'NJ',  'New Jersey'                    ),
                    (  35,   840,   'NM',  'New Mexico'                    ),
                    (  36,   840,   'NY',  'New York'                      ),
                    (  37,   840,   'NC',  'North Carolina'                ),
                    (  38,   840,   'ND',  'North Dakota'                  ),
                    (  39,   840,   'OH',  'Ohio'                          ),
                    (  40,   840,   'OK',  'Oklahoma'                      ),
                    (  41,   840,   'OR',  'Oregon'                        ),
                    (  42,   840,   'PA',  'Pennsylvania'                  ),
                    (  44,   840,   'RI',  'Rhode Island'                  ),
                    (  45,   840,   'SC',  'South Carolina'                ),
                    (  46,   840,   'SD',  'South Dakota'                  ),
                    (  47,   840,   'TN',  'Tennessee'                     ),
                    (  48,   840,   'TX',  'Texas'                         ),
                    (  49,   840,   'UT',  'Utah'                          ),
                    (  50,   840,   'VT',  'Vermont'                       ),
                    (  51,   840,   'VA',  'Virginia'                      ),
                    (  53,   840,   'WA',  'Washington'                    ),
                    (  54,   840,   'WV',  'West Virginia'                 ),
                    (  55,   840,   'WI',  'Wisconsin'                     ),
                    (  56,   840,   'WY',  'Wyoming'                       ),
                    (  60,   840,   'AS',  'American Samoa'                ),
                    (  64,   840,   'FM',  'Federated State'               ),
                    (  66,   840,   'GU',  'Guam'                          ),
                    (  67,   840,   '',    'Johnston Atoll'                ),
                    (  68,   840,   'MH',  'Marshall Island'               ),
                    (  69,   840,   'MP',  'Northern Marian'               ),
                    (  70,   840,   'PW',  'Palau'                         ),
                    (  71,   840,   '',    'Midway Islands'                ),
                    (  72,   840,   'PR',  'Puerto Rico'                   ),
                    (  74,   840,   'UM',  'U.S. Minor Outlands'           ),
                    (  76,   840,   '',    'Navassa Island'                ),
                    (  78,   840,   'VI',  'Virgin Islands '               ),
                    (  79,   840,   '',    'Wake Island'                   ),
                    (  81,   840,   '',    'Baker Island'                  ),
                    (  84,   840,   '',    'Howland Island'                ),
                    (  86,   840,   '',    'Jarvis Island'                 ),
                    (  89,   840,   '',    'Kingman Reef'                  ),
                    (  95,   840,   '',    'Palmyra Atoll'                 ),
                    (  96,   124,   'ON',  'Ontario'                       ),
                    (  97,   124,   'QC',  'Quebec'                        ),
                    (  98,   124,   'NS',  'Nova Scotia'                   ),
                    (  99,   124,   'NB',  'New Brunswick'                 ),
                    ( 100,   124,   'MB',  'Manitoba'                      ),
                    ( 101,   124,   'BC',  'British Columbia'              ),
                    ( 102,   124,   'PE',  'Prince Edward Island'          ),
                    ( 103,   124,   'SK',  'Saskatchewan'                  ),
                    ( 104,   124,   'AB',  'Alberta'                       ),
                    ( 105,   124,   'NL',  'Newfoundland and Labrador'     ),
                    ( 106,   124,   'NT',  'Northwest Territories'         ),
                    ( 107,   124,   'YT',  'Yukon Territories'             ),
                    ( 108,   124,   'NU',  'Nunavut'                       ),
                    ( 109,   484,   'AG',   'Aguascalientes'               ),
                    ( 110,   484,   'BC',   'Baja California Norte'        ),
                    ( 111,   484,   'BS',   'Baja California Sur'          ),
                    ( 112,   484,   'CH',   'Chihuahua'                    ),
                    ( 113,   484,   'CL',   'Colima'                       ),
                    ( 114,   484,   'CM',   'Campeche'                     ),
                    ( 115,   484,   'CO',   'Coahuila'                     ),
                    ( 116,   484,   'CS',   'Chiapas'                      ),
                    ( 117,   484,   'DF',   'Distrito Federal'             ),
                    ( 118,   484,   'DG',   'Durango'                      ),
                    ( 119,   484,   'GR',   'Guerrero'                     ),
                    ( 120,   484,   'GT',   'Guanajuato'                   ),
                    ( 121,   484,   'HG',   'Hidalgo'                      ),
                    ( 122,   484,   'JA',   'Jalisco'                      ),
                    ( 123,   484,   'MI',   'Michoacan'                    ),
                    ( 124,   484,   'MO',   'Morelos'                      ),
                    ( 125,   484,   'NA',   'Nayarit'                      ),
                    ( 126,   484,   'NL',   'Nuevo Leon'                   ),
                    ( 127,   484,   'OA',   'Oaxaca'                       ),
                    ( 128,   484,   'PU',   'Puebla'                       ),
                    ( 129,   484,   'QR',   'Quintana Roo'                 ),
                    ( 130,   484,   'QT',   'Queretaro'                    ),
                    ( 131,   484,   'SI',   'Sinaloa'                      ),
                    ( 132,   484,   'SL',   'San Luis Potosi'              ),
                    ( 133,   484,   'SO',   'Sonora  Hermosillo'           ),
                    ( 134,   484,   'TB',   'Tabasco'                      ),
                    ( 135,   484,   'TL',   'Tlaxcala'                     ),
                    ( 136,   484,   'TM',   'Tamaulipas'                   ),
                    ( 137,   484,   'VE',   'Veracruz'                     ),
                    ( 138,   484,   'YU',   'Yucatan'                      ),
                    ( 139,   484,   'ZA',   'Zacatecas'                    ) ;

-- <eof>
